run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  # Start with default linters only
  # Additional linters can be enabled incrementally as existing issues are fixed
  disable-all: true
  enable:
    - govet
    - ineffassign

linters-settings:
  govet:
    disable:
      - shadow
      - fieldalignment

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
